### ISSUE TITLE
Duplicate templates

### ISSUE THREAD

**Issue by queesamor** [oliyh/slacky#28] opened 2017-09-13 16:49 UTC
It appears that if a template is created multiple times with the same name, it will register as multiple templates, and when referencing the template for future use, only the first version will be used.

**Comment by oliyh** [comment] 2017-09-14 06:57
Hi @queesamor,

Thanks for the report. I think this is a duplicate of #25. Would you expect the later version to overwrite the first?

Thanks

**Comment by oliyh** [comment] 2020-11-09 11:50
Closing as can be resolved using `:delete-template` as per #27

**Closed as completed by oliyh** 2020-11-09 11:50 UTC
